//! Capstone-aligned AArch64 mnemonic enum
//! Source: https://github.com/capstone-engine/capstone/tree/next/arch/AArch64
//! (AArch64GenCSMappingInsnName.inc)

#![allow(non_camel_case_types)]

#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash, Default)]
#[repr(u16)]
pub enum Mnemonic {
    #[default]
    Invalid = 0,
    Abs,
    Adclb,
    Adclt,
    Adcs,
    Adc,
    Addg,
    Addha,
    Addhnb,
    Addhnt,
    Addhn,
    Addhn2,
    Addpl,
    Addpt,
    Addp,
    Addqv,
    Addspl,
    Addsvl,
    Adds,
    Addva,
    Addvl,
    Addv,
    Add,
    Adr,
    Adrp,
    Aesd,
    Aese,
    Aesimc,
    Aesmc,
    Andqv,
    Ands,
    Andv,
    And,
    Asrd,
    Asrr,
    Asr,
    AtAs1elx,
    Autda,
    Autdb,
    Autdza,
    Autdzb,
    Autia,
    Hint,
    Autia171615,
    Autiasppc,
    Autib,
    Autib171615,
    Autibsppc,
    Autiza,
    Autizb,
    Axflag,
    B,
    Bcax,
    Bc,
    Bdep,
    Bext,
    Bfdot,
    Bf1cvtl2,
    Bf1cvtlt,
    Bf1cvtl,
    Bf1cvt,
    Bf2cvtl2,
    Bf2cvtlt,
    Bf2cvtl,
    Bf2cvt,
    Bfadd,
    Bfclamp,
    Bfcvt,
    Bfcvtn,
    Bfcvtn2,
    Bfcvtnt,
    Bfmaxnm,
    Bfmax,
    Bfminnm,
    Bfmin,
    Bfmlalb,
    Bfmlalt,
    Bfmlal,
    Bfmla,
    Bfmlslb,
    Bfmlslt,
    Bfmlsl,
    Bfmls,
    Bfmmla,
    Bfmopa,
    Bfmops,
    Bfmul,
    Bfm,
    Bfsub,
    Bfvdot,
    Bgrp,
    Bics,
    Bic,
    Bif,
    Bit,
    Bl,
    Blr,
    Blraa,
    Blraaz,
    Blrab,
    Blrabz,
    Bmopa,
    Bmops,
    Br,
    Braa,
    Braaz,
    Brab,
    Brabz,
    Brb,
    Brk,
    Brkas,
    Brka,
    Brkbs,
    Brkb,
    Brkns,
    Brkn,
    Brkpas,
    Brkpa,
    Brkpbs,
    Brkpb,
    Bsl1n,
    Bsl2n,
    Bsl,
    Bti,
    Cadd,
    Casab,
    Casah,
    Casalb,
    Casalh,
    Casal,
    Casa,
    Casb,
    Cash,
    Caslb,
    Caslh,
    Casl,
    Caspal,
    Caspa,
    Caspl,
    Casp,
    Cas,
    Cbnz,
    Cbz,
    Ccmn,
    Ccmp,
    Cdot,
    Cfinv,
    Clasta,
    Clastb,
    Clr,
    Clrbhb,
    Clrex,
    Cls,
    Clz,
    Cmeq,
    Cmge,
    Cmgt,
    Cmhi,
    Cmhs,
    Cmla,
    Cmle,
    Cmlt,
    Cmpeq,
    Cmpge,
    Cmpgt,
    Cmphi,
    Cmphs,
    Cmple,
    Cmplo,
    Cmpls,
    Cmplt,
    Cmpne,
    Cmtst,
    Cnot,
    Cntb,
    Cntd,
    Cnth,
    Cntp,
    Cntw,
    Cnt,
    Compact,
    Cpye,
    Cpyen,
    Cpyern,
    Cpyert,
    Cpyertn,
    Cpyertrn,
    Cpyertwn,
    Cpyet,
    Cpyetn,
    Cpyetrn,
    Cpyetwn,
    Cpyewn,
    Cpyewt,
    Cpyewtn,
    Cpyewtrn,
    Cpyewtwn,
    Cpyfe,
    Cpyfen,
    Cpyfern,
    Cpyfert,
    Cpyfertn,
    Cpyfertrn,
    Cpyfertwn,
    Cpyfet,
    Cpyfetn,
    Cpyfetrn,
    Cpyfetwn,
    Cpyfewn,
    Cpyfewt,
    Cpyfewtn,
    Cpyfewtrn,
    Cpyfewtwn,
    Cpyfm,
    Cpyfmn,
    Cpyfmrn,
    Cpyfmrt,
    Cpyfmrtn,
    Cpyfmrtrn,
    Cpyfmrtwn,
    Cpyfmt,
    Cpyfmtn,
    Cpyfmtrn,
    Cpyfmtwn,
    Cpyfmwn,
    Cpyfmwt,
    Cpyfmwtn,
    Cpyfmwtrn,
    Cpyfmwtwn,
    Cpyfp,
    Cpyfpn,
    Cpyfprn,
    Cpyfprt,
    Cpyfprtn,
    Cpyfprtrn,
    Cpyfprtwn,
    Cpyfpt,
    Cpyfptn,
    Cpyfptrn,
    Cpyfptwn,
    Cpyfpwn,
    Cpyfpwt,
    Cpyfpwtn,
    Cpyfpwtrn,
    Cpyfpwtwn,
    Cpym,
    Cpymn,
    Cpymrn,
    Cpymrt,
    Cpymrtn,
    Cpymrtrn,
    Cpymrtwn,
    Cpymt,
    Cpymtn,
    Cpymtrn,
    Cpymtwn,
    Cpymwn,
    Cpymwt,
    Cpymwtn,
    Cpymwtrn,
    Cpymwtwn,
    Cpyp,
    Cpypn,
    Cpyprn,
    Cpyprt,
    Cpyprtn,
    Cpyprtrn,
    Cpyprtwn,
    Cpypt,
    Cpyptn,
    Cpyptrn,
    Cpyptwn,
    Cpypwn,
    Cpypwt,
    Cpypwtn,
    Cpypwtrn,
    Cpypwtwn,
    Cpy,
    Crc32b,
    Crc32cb,
    Crc32ch,
    Crc32cw,
    Crc32cx,
    Crc32h,
    Crc32w,
    Crc32x,
    Csel,
    Csinc,
    Csinv,
    Csneg,
    Ctermeq,
    Ctermne,
    Ctz,
    Dcps1,
    Dcps2,
    Dcps3,
    Decb,
    Decd,
    Dech,
    Decp,
    Decw,
    Dmb,
    Drps,
    Dsb,
    Dupm,
    Dupq,
    Dup,
    Mov,
    Eon,
    Eor3,
    Eorbt,
    Eorqv,
    Eors,
    Eortb,
    Eorv,
    Eor,
    Eret,
    Eretaa,
    Eretab,
    Extq,
    Mova,
    Extr,
    Extrx,
    Extry,
    Ext,
    F1cvtl2,
    F1cvtlt,
    F1cvtl,
    F1cvt,
    F2cvtl2,
    F2cvtlt,
    F2cvtl,
    F2cvt,
    Fabd,
    Fabs,
    Facge,
    Facgt,
    Fadda,
    Fadd,
    Faddp,
    Faddqv,
    Faddv,
    Famax,
    Famin,
    Fcadd,
    Fccmp,
    Fccmpe,
    Fclamp,
    Fcmeq,
    Fcmge,
    Fcmgt,
    Fcmla,
    Fcmle,
    Fcmlt,
    Fcmne,
    Fcmp,
    Fcmpe,
    Fcmuo,
    Fcpy,
    Fcsel,
    Fcvtas,
    Fcvtau,
    Fcvt,
    Fcvtlt,
    Fcvtl,
    Fcvtl2,
    Fcvtms,
    Fcvtmu,
    Fcvtnb,
    Fcvtns,
    Fcvtnt,
    Fcvtnu,
    Fcvtn,
    Fcvtn2,
    Fcvtps,
    Fcvtpu,
    Fcvtxnt,
    Fcvtxn,
    Fcvtxn2,
    Fcvtx,
    Fcvtzs,
    Fcvtzu,
    Fdiv,
    Fdivr,
    Fdot,
    Fdup,
    Fexpa,
    Fjcvtzs,
    Flogb,
    Fma16,
    Fma32,
    Fma64,
    Fmadd,
    Fmad,
    Fmax,
    Fmaxnm,
    Fmaxnmp,
    Fmaxnmqv,
    Fmaxnmv,
    Fmaxp,
    Fmaxqv,
    Fmaxv,
    Fmin,
    Fminnm,
    Fminnmp,
    Fminnmqv,
    Fminnmv,
    Fminp,
    Fminqv,
    Fminv,
    Fmlal2,
    Fmlalb,
    Fmlallbb,
    Fmlallbt,
    Fmlalltb,
    Fmlalltt,
    Fmlall,
    Fmlalt,
    Fmlal,
    Fmla,
    Fmlsl2,
    Fmlslb,
    Fmlslt,
    Fmlsl,
    Fmls,
    Fmmla,
    Fmopa,
    Fmops,
    Fmov,
    Fms16,
    Fms32,
    Fms64,
    Fmsb,
    Fmsub,
    Fmul,
    Fmulx,
    Fneg,
    Fnmadd,
    Fnmad,
    Fnmla,
    Fnmls,
    Fnmsb,
    Fnmsub,
    Fnmul,
    Frecpe,
    Frecps,
    Frecpx,
    Frint32x,
    Frint32z,
    Frint64x,
    Frint64z,
    Frinta,
    Frinti,
    Frintm,
    Frintn,
    Frintp,
    Frintx,
    Frintz,
    Frsqrte,
    Frsqrts,
    Fscale,
    Fsqrt,
    Fsub,
    Fsubr,
    Ftmad,
    Ftsmul,
    Ftssel,
    Fvdotb,
    Fvdott,
    Fvdot,
    Gcspopcx,
    Gcspopm,
    Gcspopx,
    Gcspushm,
    Gcspushx,
    Gcsss1,
    Gcsss2,
    Gcsstr,
    Gcssttr,
    Genlut,
    Genter,
    Gexit,
    Ld1b,
    Ld1d,
    Ld1h,
    Ld1q,
    Ld1sb,
    Ld1sh,
    Ld1sw,
    Ld1w,
    Ldff1b,
    Ldff1d,
    Ldff1h,
    Ldff1sb,
    Ldff1sh,
    Ldff1sw,
    Ldff1w,
    Gmi,
    Histcnt,
    Histseg,
    Hlt,
    Hvc,
    Incb,
    Incd,
    Inch,
    Incp,
    Incw,
    Index,
    Insr,
    Ins,
    Irg,
    Isb,
    Lasta,
    Lastb,
    Ld1,
    Ld1rb,
    Ld1rd,
    Ld1rh,
    Ld1rob,
    Ld1rod,
    Ld1roh,
    Ld1row,
    Ld1rqb,
    Ld1rqd,
    Ld1rqh,
    Ld1rqw,
    Ld1rsb,
    Ld1rsh,
    Ld1rsw,
    Ld1rw,
    Ld1r,
    Ld2b,
    Ld2d,
    Ld2h,
    Ld2q,
    Ld2r,
    Ld2,
    Ld2w,
    Ld3b,
    Ld3d,
    Ld3h,
    Ld3q,
    Ld3r,
    Ld3,
    Ld3w,
    Ld4b,
    Ld4d,
    Ld4,
    Ld4h,
    Ld4q,
    Ld4r,
    Ld4w,
    Ld64b,
    Ldaddab,
    Ldaddah,
    Ldaddalb,
    Ldaddalh,
    Ldaddal,
    Ldadda,
    Ldaddb,
    Ldaddh,
    Ldaddlb,
    Ldaddlh,
    Ldaddl,
    Ldadd,
    Ldap1,
    Ldaprb,
    Ldaprh,
    Ldapr,
    Ldapurb,
    Ldapurh,
    Ldapursb,
    Ldapursh,
    Ldapursw,
    Ldapur,
    Ldarb,
    Ldarh,
    Ldar,
    Ldaxp,
    Ldaxrb,
    Ldaxrh,
    Ldaxr,
    Ldclrab,
    Ldclrah,
    Ldclralb,
    Ldclralh,
    Ldclral,
    Ldclra,
    Ldclrb,
    Ldclrh,
    Ldclrlb,
    Ldclrlh,
    Ldclrl,
    Ldclrp,
    Ldclrpa,
    Ldclrpal,
    Ldclrpl,
    Ldclr,
    Ldeorab,
    Ldeorah,
    Ldeoralb,
    Ldeoralh,
    Ldeoral,
    Ldeora,
    Ldeorb,
    Ldeorh,
    Ldeorlb,
    Ldeorlh,
    Ldeorl,
    Ldeor,
    Ldg,
    Ldgm,
    Ldiapp,
    Ldlarb,
    Ldlarh,
    Ldlar,
    Ldnf1b,
    Ldnf1d,
    Ldnf1h,
    Ldnf1sb,
    Ldnf1sh,
    Ldnf1sw,
    Ldnf1w,
    Ldnp,
    Ldnt1b,
    Ldnt1d,
    Ldnt1h,
    Ldnt1sb,
    Ldnt1sh,
    Ldnt1sw,
    Ldnt1w,
    Ldp,
    Ldpsw,
    Ldraa,
    Ldrab,
    Ldrb,
    Ldr,
    Ldrh,
    Ldrsb,
    Ldrsh,
    Ldrsw,
    Ldsetab,
    Ldsetah,
    Ldsetalb,
    Ldsetalh,
    Ldsetal,
    Ldseta,
    Ldsetb,
    Ldseth,
    Ldsetlb,
    Ldsetlh,
    Ldsetl,
    Ldsetp,
    Ldsetpa,
    Ldsetpal,
    Ldsetpl,
    Ldset,
    Ldsmaxab,
    Ldsmaxah,
    Ldsmaxalb,
    Ldsmaxalh,
    Ldsmaxal,
    Ldsmaxa,
    Ldsmaxb,
    Ldsmaxh,
    Ldsmaxlb,
    Ldsmaxlh,
    Ldsmaxl,
    Ldsmax,
    Ldsminab,
    Ldsminah,
    Ldsminalb,
    Ldsminalh,
    Ldsminal,
    Ldsmina,
    Ldsminb,
    Ldsminh,
    Ldsminlb,
    Ldsminlh,
    Ldsminl,
    Ldsmin,
    Ldtrb,
    Ldtrh,
    Ldtrsb,
    Ldtrsh,
    Ldtrsw,
    Ldtr,
    Ldumaxab,
    Ldumaxah,
    Ldumaxalb,
    Ldumaxalh,
    Ldumaxal,
    Ldumaxa,
    Ldumaxb,
    Ldumaxh,
    Ldumaxlb,
    Ldumaxlh,
    Ldumaxl,
    Ldumax,
    Lduminab,
    Lduminah,
    Lduminalb,
    Lduminalh,
    Lduminal,
    Ldumina,
    Lduminb,
    Lduminh,
    Lduminlb,
    Lduminlh,
    Lduminl,
    Ldumin,
    Ldurb,
    Ldur,
    Ldurh,
    Ldursb,
    Ldursh,
    Ldursw,
    Ldx,
    Ldxp,
    Ldxrb,
    Ldxrh,
    Ldxr,
    Ldy,
    Ldz,
    Ldzi,
    Lslr,
    Lsl,
    Lsrr,
    Lsr,
    Luti2,
    Luti4,
    Mac16,
    Maddpt,
    Madd,
    Madpt,
    Mad,
    Match,
    Matfp,
    Matint,
    Mlapt,
    Mla,
    Mls,
    Setge,
    Setgen,
    Setget,
    Setgetn,
    Movaz,
    Movi,
    Movk,
    Movn,
    Movprfx,
    Movt,
    Movz,
    Mrrs,
    Mrs,
    Msb,
    Msr,
    Msrr,
    Msubpt,
    Msub,
    Mul53hi,
    Mul53lo,
    Mul,
    Mvni,
    Nands,
    Nand,
    Nbsl,
    Neg,
    Nmatch,
    Nors,
    Nor,
    Not,
    Orns,
    Orn,
    Orqv,
    Orrs,
    Orr,
    Orv,
    Pacda,
    Pacdb,
    Pacdza,
    Pacdzb,
    Pacga,
    Pacia,
    Pacia171615,
    Paciasppc,
    Pacib,
    Pacib171615,
    Pacibsppc,
    Paciza,
    Pacizb,
    Pacnbiasppc,
    Pacnbibsppc,
    Pext,
    Pfalse,
    Pfirst,
    Pmov,
    Pmullb,
    Pmullt,
    Pmull2,
    Pmull,
    Pmul,
    Pnext,
    Prfb,
    Prfd,
    Prfh,
    Prfm,
    Prfum,
    Prfw,
    Psel,
    Ptest,
    Ptrues,
    Ptrue,
    Punpkhi,
    Punpklo,
    Raddhnb,
    Raddhnt,
    Raddhn,
    Raddhn2,
    Rax1,
    Rbit,
    Rcwcas,
    Rcwcasa,
    Rcwcasal,
    Rcwcasl,
    Rcwcasp,
    Rcwcaspa,
    Rcwcaspal,
    Rcwcaspl,
    Rcwclr,
    Rcwclra,
    Rcwclral,
    Rcwclrl,
    Rcwclrp,
    Rcwclrpa,
    Rcwclrpal,
    Rcwclrpl,
    Rcwsclr,
    Rcwsclra,
    Rcwsclral,
    Rcwsclrl,
    Rcwsclrp,
    Rcwsclrpa,
    Rcwsclrpal,
    Rcwsclrpl,
    Rcwscas,
    Rcwscasa,
    Rcwscasal,
    Rcwscasl,
    Rcwscasp,
    Rcwscaspa,
    Rcwscaspal,
    Rcwscaspl,
    Rcwset,
    Rcwseta,
    Rcwsetal,
    Rcwsetl,
    Rcwsetp,
    Rcwsetpa,
    Rcwsetpal,
    Rcwsetpl,
    Rcwsset,
    Rcwsseta,
    Rcwssetal,
    Rcwssetl,
    Rcwssetp,
    Rcwssetpa,
    Rcwssetpal,
    Rcwssetpl,
    Rcwswp,
    Rcwswpa,
    Rcwswpal,
    Rcwswpl,
    Rcwswpp,
    Rcwswppa,
    Rcwswppal,
    Rcwswppl,
    Rcwsswp,
    Rcwsswpa,
    Rcwsswpal,
    Rcwsswpl,
    Rcwsswpp,
    Rcwsswppa,
    Rcwsswppal,
    Rcwsswppl,
    Rdffrs,
    Rdffr,
    Rdsvl,
    Rdvl,
    Ret,
    Retaa,
    Retaasppc,
    Retab,
    Retabsppc,
    Rev16,
    Rev32,
    Rev64,
    Revb,
    Revd,
    Revh,
    Revw,
    Rev,
    Rmif,
    Ror,
    Rprfm,
    Rshrnb,
    Rshrnt,
    Rshrn2,
    Rshrn,
    Rsubhnb,
    Rsubhnt,
    Rsubhn,
    Rsubhn2,
    Sabalb,
    Sabalt,
    Sabal2,
    Sabal,
    Saba,
    Sabdlb,
    Sabdlt,
    Sabdl2,
    Sabdl,
    Sabd,
    Sadalp,
    Saddlbt,
    Saddlb,
    Saddlp,
    Saddlt,
    Saddlv,
    Saddl2,
    Saddl,
    Saddv,
    Saddwb,
    Saddwt,
    Saddw2,
    Saddw,
    Sb,
    Sbclb,
    Sbclt,
    Sbcs,
    Sbc,
    Sbfm,
    Sclamp,
    Scvtf,
    Sdivr,
    Sdiv,
    Sdot,
    Sdsb,
    Sel,
    Set,
    Sete,
    Seten,
    Setet,
    Setetn,
    Setf16,
    Setf8,
    Setffr,
    Setgm,
    Setgmn,
    Setgmt,
    Setgmtn,
    Setgp,
    Setgpn,
    Setgpt,
    Setgptn,
    Setm,
    Setmn,
    Setmt,
    Setmtn,
    Setp,
    Setpn,
    Setpt,
    Setptn,
    Sha1c,
    Sha1h,
    Sha1m,
    Sha1p,
    Sha1su0,
    Sha1su1,
    Sha256h2,
    Sha256h,
    Sha256su0,
    Sha256su1,
    Sha512h,
    Sha512h2,
    Sha512su0,
    Sha512su1,
    Shadd,
    Shll2,
    Shll,
    Shl,
    Shrnb,
    Shrnt,
    Shrn2,
    Shrn,
    Shsubr,
    Shsub,
    Sli,
    Sm3partw1,
    Sm3partw2,
    Sm3ss1,
    Sm3tt1a,
    Sm3tt1b,
    Sm3tt2a,
    Sm3tt2b,
    Sm4e,
    Sm4ekey,
    Smaddl,
    Smaxp,
    Smaxqv,
    Smaxv,
    Smax,
    Smc,
    Sminp,
    Sminqv,
    Sminv,
    Smin,
    Smlalb,
    Smlall,
    Smlalt,
    Smlal,
    Smlal2,
    Smlslb,
    Smlsll,
    Smlslt,
    Smlsl,
    Smlsl2,
    Smmla,
    Smopa,
    Smops,
    Smov,
    Smsubl,
    Smulh,
    Smullb,
    Smullt,
    Smull2,
    Smull,
    Splice,
    Sqabs,
    Sqadd,
    Sqcadd,
    Sqcvtn,
    Sqcvtun,
    Sqcvtu,
    Sqcvt,
    Sqdecb,
    Sqdecd,
    Sqdech,
    Sqdecp,
    Sqdecw,
    Sqdmlalbt,
    Sqdmlalb,
    Sqdmlalt,
    Sqdmlal,
    Sqdmlal2,
    Sqdmlslbt,
    Sqdmlslb,
    Sqdmlslt,
    Sqdmlsl,
    Sqdmlsl2,
    Sqdmulh,
    Sqdmullb,
    Sqdmullt,
    Sqdmull,
    Sqdmull2,
    Sqincb,
    Sqincd,
    Sqinch,
    Sqincp,
    Sqincw,
    Sqneg,
    Sqrdcmlah,
    Sqrdmlah,
    Sqrdmlsh,
    Sqrdmulh,
    Sqrshlr,
    Sqrshl,
    Sqrshrnb,
    Sqrshrnt,
    Sqrshrn,
    Sqrshrn2,
    Sqrshrunb,
    Sqrshrunt,
    Sqrshrun,
    Sqrshrun2,
    Sqrshru,
    Sqrshr,
    Sqshlr,
    Sqshlu,
    Sqshl,
    Sqshrnb,
    Sqshrnt,
    Sqshrn,
    Sqshrn2,
    Sqshrunb,
    Sqshrunt,
    Sqshrun,
    Sqshrun2,
    Sqsubr,
    Sqsub,
    Sqxtnb,
    Sqxtnt,
    Sqxtn2,
    Sqxtn,
    Sqxtunb,
    Sqxtunt,
    Sqxtun2,
    Sqxtun,
    Srhadd,
    Sri,
    Srshlr,
    Srshl,
    Srshr,
    Srsra,
    Sshllb,
    Sshllt,
    Sshll2,
    Sshll,
    Sshl,
    Sshr,
    Ssra,
    St1b,
    St1d,
    St1h,
    St1q,
    St1w,
    Ssublbt,
    Ssublb,
    Ssubltb,
    Ssublt,
    Ssubl2,
    Ssubl,
    Ssubwb,
    Ssubwt,
    Ssubw2,
    Ssubw,
    St1,
    St2b,
    St2d,
    St2g,
    St2h,
    St2q,
    St2,
    St2w,
    St3b,
    St3d,
    St3h,
    St3q,
    St3,
    St3w,
    St4b,
    St4d,
    St4,
    St4h,
    St4q,
    St4w,
    St64b,
    St64bv,
    St64bv0,
    Stadd,
    Stclr,
    Steorl,
    Steor,
    Stsetl,
    Stset,
    Stsmaxl,
    Stsmax,
    Stsminl,
    Stsmin,
    Stumax,
    Stumin,
    Stgm,
    Stgp,
    Stg,
    Stilp,
    Stl1,
    Stllrb,
    Stllrh,
    Stllr,
    Stlrb,
    Stlrh,
    Stlr,
    Stlurb,
    Stlurh,
    Stlur,
    Stlxp,
    Stlxrb,
    Stlxrh,
    Stlxr,
    Stnp,
    Stnt1b,
    Stnt1d,
    Stnt1h,
    Stnt1w,
    Stp,
    Strb,
    Str,
    Strh,
    Sttrb,
    Sttrh,
    Sttr,
    Sturb,
    Stur,
    Sturh,
    Stx,
    Stxp,
    Stxrb,
    Stxrh,
    Stxr,
    Sty,
    Stz,
    Stz2g,
    Stzgm,
    Stzg,
    Stzi,
    Subg,
    Subhnb,
    Subhnt,
    Subhn,
    Subhn2,
    Subp,
    Subps,
    Subpt,
    Subr,
    Subs,
    Sub,
    Sudot,
    Sumlall,
    Sumopa,
    Sumops,
    Sunpkhi,
    Sunpklo,
    Sunpk,
    Suqadd,
    Suvdot,
    Svc,
    Svdot,
    Swpab,
    Swpah,
    Swpalb,
    Swpalh,
    Swpal,
    Swpa,
    Swpb,
    Swph,
    Swplb,
    Swplh,
    Swpl,
    Swpp,
    Swppa,
    Swppal,
    Swppl,
    Swp,
    Sxtb,
    Sxth,
    Sxtw,
    Sysl,
    Sysp,
    Sys,
    Tlbi,
    At,
    Dc,
    Ic,
    Tblq,
    Tbl,
    Tbnz,
    Tbxq,
    Tbx,
    Tbz,
    Tcancel,
    Tcommit,
    Trcit,
    Trn1,
    Trn2,
    Tsb,
    Tstart,
    Ttest,
    Uabalb,
    Uabalt,
    Uabal2,
    Uabal,
    Uaba,
    Uabdlb,
    Uabdlt,
    Uabdl2,
    Uabdl,
    Uabd,
    Uadalp,
    Uaddlb,
    Uaddlp,
    Uaddlt,
    Uaddlv,
    Uaddl2,
    Uaddl,
    Uaddv,
    Uaddwb,
    Uaddwt,
    Uaddw2,
    Uaddw,
    Ubfm,
    Uclamp,
    Ucvtf,
    Udf,
    Udivr,
    Udiv,
    Udot,
    Uhadd,
    Uhsubr,
    Uhsub,
    Umaddl,
    Umaxp,
    Umaxqv,
    Umaxv,
    Umax,
    Uminp,
    Uminqv,
    Uminv,
    Umin,
    Umlalb,
    Umlall,
    Umlalt,
    Umlal,
    Umlal2,
    Umlslb,
    Umlsll,
    Umlslt,
    Umlsl,
    Umlsl2,
    Ummla,
    Umopa,
    Umops,
    Umov,
    Umsubl,
    Umulh,
    Umullb,
    Umullt,
    Umull2,
    Umull,
    Uqadd,
    Uqcvtn,
    Uqcvt,
    Uqdecb,
    Uqdecd,
    Uqdech,
    Uqdecp,
    Uqdecw,
    Uqincb,
    Uqincd,
    Uqinch,
    Uqincp,
    Uqincw,
    Uqrshlr,
    Uqrshl,
    Uqrshrnb,
    Uqrshrnt,
    Uqrshrn,
    Uqrshrn2,
    Uqrshr,
    Uqshlr,
    Uqshl,
    Uqshrnb,
    Uqshrnt,
    Uqshrn,
    Uqshrn2,
    Uqsubr,
    Uqsub,
    Uqxtnb,
    Uqxtnt,
    Uqxtn2,
    Uqxtn,
    Urecpe,
    Urhadd,
    Urshlr,
    Urshl,
    Urshr,
    Ursqrte,
    Ursra,
    Usdot,
    Ushllb,
    Ushllt,
    Ushll2,
    Ushll,
    Ushl,
    Ushr,
    Usmlall,
    Usmmla,
    Usmopa,
    Usmops,
    Usqadd,
    Usra,
    Usublb,
    Usublt,
    Usubl2,
    Usubl,
    Usubwb,
    Usubwt,
    Usubw2,
    Usubw,
    Usvdot,
    Uunpkhi,
    Uunpklo,
    Uunpk,
    Uvdot,
    Uxtb,
    Uxth,
    Uxtw,
    Uzp1,
    Uzp2,
    Uzpq1,
    Uzpq2,
    Uzp,
    Vecfp,
    Vecint,
    Wfet,
    Wfit,
    Whilege,
    Whilegt,
    Whilehi,
    Whilehs,
    Whilele,
    Whilelo,
    Whilels,
    Whilelt,
    Whilerw,
    Whilewr,
    Wkdmc,
    Wkdmd,
    Wrffr,
    Xaflag,
    Xar,
    Xpacd,
    Xpaci,
    Xtn2,
    Xtn,
    Zero,
    Zip1,
    Zip2,
    Zipq1,
    Zipq2,
    Zip,
    Nop,
    Yield,
    Wfe,
    Wfi,
    Sev,
    Sevl,
    Paciasp,
    Pacibsp,
    Autia1716,
    Autib1716,
    Autiasp,
    Autibsp,
    Retabsp,
    Bcond,
    Cmn,
    Tst,
    Negs,
    Mvn,
    Cset,
    Csetm,
    Cinc,
    Cinv,
    Cneg,
    Mneg,
    Cmp,
    Undefined,
}

impl Mnemonic {
    pub fn as_str(self) -> &'static str {
        use Mnemonic::*;
        match self {
            Invalid => "invalid",
            Abs => "abs",
            Adclb => "adclb",
            Adclt => "adclt",
            Adcs => "adcs",
            Adc => "adc",
            Addg => "addg",
            Addha => "addha",
            Addhnb => "addhnb",
            Addhnt => "addhnt",
            Addhn => "addhn",
            Addhn2 => "addhn2",
            Addpl => "addpl",
            Addpt => "addpt",
            Addp => "addp",
            Addqv => "addqv",
            Addspl => "addspl",
            Addsvl => "addsvl",
            Adds => "adds",
            Addva => "addva",
            Addvl => "addvl",
            Addv => "addv",
            Add => "add",
            Adr => "adr",
            Adrp => "adrp",
            Aesd => "aesd",
            Aese => "aese",
            Aesimc => "aesimc",
            Aesmc => "aesmc",
            Andqv => "andqv",
            Ands => "ands",
            Andv => "andv",
            And => "and",
            Asrd => "asrd",
            Asrr => "asrr",
            Asr => "asr",
            AtAs1elx => "at_as1elx",
            Autda => "autda",
            Autdb => "autdb",
            Autdza => "autdza",
            Autdzb => "autdzb",
            Autia => "autia",
            Hint => "hint",
            Autia171615 => "autia171615",
            Autiasppc => "autiasppc",
            Autib => "autib",
            Autib171615 => "autib171615",
            Autibsppc => "autibsppc",
            Autiza => "autiza",
            Autizb => "autizb",
            Axflag => "axflag",
            B => "b",
            Bcax => "bcax",
            Bc => "bc",
            Bdep => "bdep",
            Bext => "bext",
            Bfdot => "bfdot",
            Bf1cvtl2 => "bf1cvtl2",
            Bf1cvtlt => "bf1cvtlt",
            Bf1cvtl => "bf1cvtl",
            Bf1cvt => "bf1cvt",
            Bf2cvtl2 => "bf2cvtl2",
            Bf2cvtlt => "bf2cvtlt",
            Bf2cvtl => "bf2cvtl",
            Bf2cvt => "bf2cvt",
            Bfadd => "bfadd",
            Bfclamp => "bfclamp",
            Bfcvt => "bfcvt",
            Bfcvtn => "bfcvtn",
            Bfcvtn2 => "bfcvtn2",
            Bfcvtnt => "bfcvtnt",
            Bfmaxnm => "bfmaxnm",
            Bfmax => "bfmax",
            Bfminnm => "bfminnm",
            Bfmin => "bfmin",
            Bfmlalb => "bfmlalb",
            Bfmlalt => "bfmlalt",
            Bfmlal => "bfmlal",
            Bfmla => "bfmla",
            Bfmlslb => "bfmlslb",
            Bfmlslt => "bfmlslt",
            Bfmlsl => "bfmlsl",
            Bfmls => "bfmls",
            Bfmmla => "bfmmla",
            Bfmopa => "bfmopa",
            Bfmops => "bfmops",
            Bfmul => "bfmul",
            Bfm => "bfm",
            Bfsub => "bfsub",
            Bfvdot => "bfvdot",
            Bgrp => "bgrp",
            Bics => "bics",
            Bic => "bic",
            Bif => "bif",
            Bit => "bit",
            Bl => "bl",
            Blr => "blr",
            Blraa => "blraa",
            Blraaz => "blraaz",
            Blrab => "blrab",
            Blrabz => "blrabz",
            Bmopa => "bmopa",
            Bmops => "bmops",
            Br => "br",
            Braa => "braa",
            Braaz => "braaz",
            Brab => "brab",
            Brabz => "brabz",
            Brb => "brb",
            Brk => "brk",
            Brkas => "brkas",
            Brka => "brka",
            Brkbs => "brkbs",
            Brkb => "brkb",
            Brkns => "brkns",
            Brkn => "brkn",
            Brkpas => "brkpas",
            Brkpa => "brkpa",
            Brkpbs => "brkpbs",
            Brkpb => "brkpb",
            Bsl1n => "bsl1n",
            Bsl2n => "bsl2n",
            Bsl => "bsl",
            Bti => "bti",
            Cadd => "cadd",
            Casab => "casab",
            Casah => "casah",
            Casalb => "casalb",
            Casalh => "casalh",
            Casal => "casal",
            Casa => "casa",
            Casb => "casb",
            Cash => "cash",
            Caslb => "caslb",
            Caslh => "caslh",
            Casl => "casl",
            Caspal => "caspal",
            Caspa => "caspa",
            Caspl => "caspl",
            Casp => "casp",
            Cas => "cas",
            Cbnz => "cbnz",
            Cbz => "cbz",
            Ccmn => "ccmn",
            Ccmp => "ccmp",
            Cdot => "cdot",
            Cfinv => "cfinv",
            Clasta => "clasta",
            Clastb => "clastb",
            Clr => "clr",
            Clrbhb => "clrbhb",
            Clrex => "clrex",
            Cls => "cls",
            Clz => "clz",
            Cmeq => "cmeq",
            Cmge => "cmge",
            Cmgt => "cmgt",
            Cmhi => "cmhi",
            Cmhs => "cmhs",
            Cmla => "cmla",
            Cmle => "cmle",
            Cmlt => "cmlt",
            Cmpeq => "cmpeq",
            Cmpge => "cmpge",
            Cmpgt => "cmpgt",
            Cmphi => "cmphi",
            Cmphs => "cmphs",
            Cmple => "cmple",
            Cmplo => "cmplo",
            Cmpls => "cmpls",
            Cmplt => "cmplt",
            Cmpne => "cmpne",
            Cmtst => "cmtst",
            Cnot => "cnot",
            Cntb => "cntb",
            Cntd => "cntd",
            Cnth => "cnth",
            Cntp => "cntp",
            Cntw => "cntw",
            Cnt => "cnt",
            Compact => "compact",
            Cpye => "cpye",
            Cpyen => "cpyen",
            Cpyern => "cpyern",
            Cpyert => "cpyert",
            Cpyertn => "cpyertn",
            Cpyertrn => "cpyertrn",
            Cpyertwn => "cpyertwn",
            Cpyet => "cpyet",
            Cpyetn => "cpyetn",
            Cpyetrn => "cpyetrn",
            Cpyetwn => "cpyetwn",
            Cpyewn => "cpyewn",
            Cpyewt => "cpyewt",
            Cpyewtn => "cpyewtn",
            Cpyewtrn => "cpyewtrn",
            Cpyewtwn => "cpyewtwn",
            Cpyfe => "cpyfe",
            Cpyfen => "cpyfen",
            Cpyfern => "cpyfern",
            Cpyfert => "cpyfert",
            Cpyfertn => "cpyfertn",
            Cpyfertrn => "cpyfertrn",
            Cpyfertwn => "cpyfertwn",
            Cpyfet => "cpyfet",
            Cpyfetn => "cpyfetn",
            Cpyfetrn => "cpyfetrn",
            Cpyfetwn => "cpyfetwn",
            Cpyfewn => "cpyfewn",
            Cpyfewt => "cpyfewt",
            Cpyfewtn => "cpyfewtn",
            Cpyfewtrn => "cpyfewtrn",
            Cpyfewtwn => "cpyfewtwn",
            Cpyfm => "cpyfm",
            Cpyfmn => "cpyfmn",
            Cpyfmrn => "cpyfmrn",
            Cpyfmrt => "cpyfmrt",
            Cpyfmrtn => "cpyfmrtn",
            Cpyfmrtrn => "cpyfmrtrn",
            Cpyfmrtwn => "cpyfmrtwn",
            Cpyfmt => "cpyfmt",
            Cpyfmtn => "cpyfmtn",
            Cpyfmtrn => "cpyfmtrn",
            Cpyfmtwn => "cpyfmtwn",
            Cpyfmwn => "cpyfmwn",
            Cpyfmwt => "cpyfmwt",
            Cpyfmwtn => "cpyfmwtn",
            Cpyfmwtrn => "cpyfmwtrn",
            Cpyfmwtwn => "cpyfmwtwn",
            Cpyfp => "cpyfp",
            Cpyfpn => "cpyfpn",
            Cpyfprn => "cpyfprn",
            Cpyfprt => "cpyfprt",
            Cpyfprtn => "cpyfprtn",
            Cpyfprtrn => "cpyfprtrn",
            Cpyfprtwn => "cpyfprtwn",
            Cpyfpt => "cpyfpt",
            Cpyfptn => "cpyfptn",
            Cpyfptrn => "cpyfptrn",
            Cpyfptwn => "cpyfptwn",
            Cpyfpwn => "cpyfpwn",
            Cpyfpwt => "cpyfpwt",
            Cpyfpwtn => "cpyfpwtn",
            Cpyfpwtrn => "cpyfpwtrn",
            Cpyfpwtwn => "cpyfpwtwn",
            Cpym => "cpym",
            Cpymn => "cpymn",
            Cpymrn => "cpymrn",
            Cpymrt => "cpymrt",
            Cpymrtn => "cpymrtn",
            Cpymrtrn => "cpymrtrn",
            Cpymrtwn => "cpymrtwn",
            Cpymt => "cpymt",
            Cpymtn => "cpymtn",
            Cpymtrn => "cpymtrn",
            Cpymtwn => "cpymtwn",
            Cpymwn => "cpymwn",
            Cpymwt => "cpymwt",
            Cpymwtn => "cpymwtn",
            Cpymwtrn => "cpymwtrn",
            Cpymwtwn => "cpymwtwn",
            Cpyp => "cpyp",
            Cpypn => "cpypn",
            Cpyprn => "cpyprn",
            Cpyprt => "cpyprt",
            Cpyprtn => "cpyprtn",
            Cpyprtrn => "cpyprtrn",
            Cpyprtwn => "cpyprtwn",
            Cpypt => "cpypt",
            Cpyptn => "cpyptn",
            Cpyptrn => "cpyptrn",
            Cpyptwn => "cpyptwn",
            Cpypwn => "cpypwn",
            Cpypwt => "cpypwt",
            Cpypwtn => "cpypwtn",
            Cpypwtrn => "cpypwtrn",
            Cpypwtwn => "cpypwtwn",
            Cpy => "cpy",
            Crc32b => "crc32b",
            Crc32cb => "crc32cb",
            Crc32ch => "crc32ch",
            Crc32cw => "crc32cw",
            Crc32cx => "crc32cx",
            Crc32h => "crc32h",
            Crc32w => "crc32w",
            Crc32x => "crc32x",
            Csel => "csel",
            Csinc => "csinc",
            Csinv => "csinv",
            Csneg => "csneg",
            Ctermeq => "ctermeq",
            Ctermne => "ctermne",
            Ctz => "ctz",
            Dcps1 => "dcps1",
            Dcps2 => "dcps2",
            Dcps3 => "dcps3",
            Decb => "decb",
            Decd => "decd",
            Dech => "dech",
            Decp => "decp",
            Decw => "decw",
            Dmb => "dmb",
            Drps => "drps",
            Dsb => "dsb",
            Dupm => "dupm",
            Dupq => "dupq",
            Dup => "dup",
            Mov => "mov",
            Eon => "eon",
            Eor3 => "eor3",
            Eorbt => "eorbt",
            Eorqv => "eorqv",
            Eors => "eors",
            Eortb => "eortb",
            Eorv => "eorv",
            Eor => "eor",
            Eret => "eret",
            Eretaa => "eretaa",
            Eretab => "eretab",
            Extq => "extq",
            Mova => "mova",
            Extr => "extr",
            Extrx => "extrx",
            Extry => "extry",
            Ext => "ext",
            F1cvtl2 => "f1cvtl2",
            F1cvtlt => "f1cvtlt",
            F1cvtl => "f1cvtl",
            F1cvt => "f1cvt",
            F2cvtl2 => "f2cvtl2",
            F2cvtlt => "f2cvtlt",
            F2cvtl => "f2cvtl",
            F2cvt => "f2cvt",
            Fabd => "fabd",
            Fabs => "fabs",
            Facge => "facge",
            Facgt => "facgt",
            Fadda => "fadda",
            Fadd => "fadd",
            Faddp => "faddp",
            Faddqv => "faddqv",
            Faddv => "faddv",
            Famax => "famax",
            Famin => "famin",
            Fcadd => "fcadd",
            Fccmp => "fccmp",
            Fccmpe => "fccmpe",
            Fclamp => "fclamp",
            Fcmeq => "fcmeq",
            Fcmge => "fcmge",
            Fcmgt => "fcmgt",
            Fcmla => "fcmla",
            Fcmle => "fcmle",
            Fcmlt => "fcmlt",
            Fcmne => "fcmne",
            Fcmp => "fcmp",
            Fcmpe => "fcmpe",
            Fcmuo => "fcmuo",
            Fcpy => "fcpy",
            Fcsel => "fcsel",
            Fcvtas => "fcvtas",
            Fcvtau => "fcvtau",
            Fcvt => "fcvt",
            Fcvtlt => "fcvtlt",
            Fcvtl => "fcvtl",
            Fcvtl2 => "fcvtl2",
            Fcvtms => "fcvtms",
            Fcvtmu => "fcvtmu",
            Fcvtnb => "fcvtnb",
            Fcvtns => "fcvtns",
            Fcvtnt => "fcvtnt",
            Fcvtnu => "fcvtnu",
            Fcvtn => "fcvtn",
            Fcvtn2 => "fcvtn2",
            Fcvtps => "fcvtps",
            Fcvtpu => "fcvtpu",
            Fcvtxnt => "fcvtxnt",
            Fcvtxn => "fcvtxn",
            Fcvtxn2 => "fcvtxn2",
            Fcvtx => "fcvtx",
            Fcvtzs => "fcvtzs",
            Fcvtzu => "fcvtzu",
            Fdiv => "fdiv",
            Fdivr => "fdivr",
            Fdot => "fdot",
            Fdup => "fdup",
            Fexpa => "fexpa",
            Fjcvtzs => "fjcvtzs",
            Flogb => "flogb",
            Fma16 => "fma16",
            Fma32 => "fma32",
            Fma64 => "fma64",
            Fmadd => "fmadd",
            Fmad => "fmad",
            Fmax => "fmax",
            Fmaxnm => "fmaxnm",
            Fmaxnmp => "fmaxnmp",
            Fmaxnmqv => "fmaxnmqv",
            Fmaxnmv => "fmaxnmv",
            Fmaxp => "fmaxp",
            Fmaxqv => "fmaxqv",
            Fmaxv => "fmaxv",
            Fmin => "fmin",
            Fminnm => "fminnm",
            Fminnmp => "fminnmp",
            Fminnmqv => "fminnmqv",
            Fminnmv => "fminnmv",
            Fminp => "fminp",
            Fminqv => "fminqv",
            Fminv => "fminv",
            Fmlal2 => "fmlal2",
            Fmlalb => "fmlalb",
            Fmlallbb => "fmlallbb",
            Fmlallbt => "fmlallbt",
            Fmlalltb => "fmlalltb",
            Fmlalltt => "fmlalltt",
            Fmlall => "fmlall",
            Fmlalt => "fmlalt",
            Fmlal => "fmlal",
            Fmla => "fmla",
            Fmlsl2 => "fmlsl2",
            Fmlslb => "fmlslb",
            Fmlslt => "fmlslt",
            Fmlsl => "fmlsl",
            Fmls => "fmls",
            Fmmla => "fmmla",
            Fmopa => "fmopa",
            Fmops => "fmops",
            Fmov => "fmov",
            Fms16 => "fms16",
            Fms32 => "fms32",
            Fms64 => "fms64",
            Fmsb => "fmsb",
            Fmsub => "fmsub",
            Fmul => "fmul",
            Fmulx => "fmulx",
            Fneg => "fneg",
            Fnmadd => "fnmadd",
            Fnmad => "fnmad",
            Fnmla => "fnmla",
            Fnmls => "fnmls",
            Fnmsb => "fnmsb",
            Fnmsub => "fnmsub",
            Fnmul => "fnmul",
            Frecpe => "frecpe",
            Frecps => "frecps",
            Frecpx => "frecpx",
            Frint32x => "frint32x",
            Frint32z => "frint32z",
            Frint64x => "frint64x",
            Frint64z => "frint64z",
            Frinta => "frinta",
            Frinti => "frinti",
            Frintm => "frintm",
            Frintn => "frintn",
            Frintp => "frintp",
            Frintx => "frintx",
            Frintz => "frintz",
            Frsqrte => "frsqrte",
            Frsqrts => "frsqrts",
            Fscale => "fscale",
            Fsqrt => "fsqrt",
            Fsub => "fsub",
            Fsubr => "fsubr",
            Ftmad => "ftmad",
            Ftsmul => "ftsmul",
            Ftssel => "ftssel",
            Fvdotb => "fvdotb",
            Fvdott => "fvdott",
            Fvdot => "fvdot",
            Gcspopcx => "gcspopcx",
            Gcspopm => "gcspopm",
            Gcspopx => "gcspopx",
            Gcspushm => "gcspushm",
            Gcspushx => "gcspushx",
            Gcsss1 => "gcsss1",
            Gcsss2 => "gcsss2",
            Gcsstr => "gcsstr",
            Gcssttr => "gcssttr",
            Genlut => "genlut",
            Genter => "genter",
            Gexit => "gexit",
            Ld1b => "ld1b",
            Ld1d => "ld1d",
            Ld1h => "ld1h",
            Ld1q => "ld1q",
            Ld1sb => "ld1sb",
            Ld1sh => "ld1sh",
            Ld1sw => "ld1sw",
            Ld1w => "ld1w",
            Ldff1b => "ldff1b",
            Ldff1d => "ldff1d",
            Ldff1h => "ldff1h",
            Ldff1sb => "ldff1sb",
            Ldff1sh => "ldff1sh",
            Ldff1sw => "ldff1sw",
            Ldff1w => "ldff1w",
            Gmi => "gmi",
            Histcnt => "histcnt",
            Histseg => "histseg",
            Hlt => "hlt",
            Hvc => "hvc",
            Incb => "incb",
            Incd => "incd",
            Inch => "inch",
            Incp => "incp",
            Incw => "incw",
            Index => "index",
            Insr => "insr",
            Ins => "ins",
            Irg => "irg",
            Isb => "isb",
            Lasta => "lasta",
            Lastb => "lastb",
            Ld1 => "ld1",
            Ld1rb => "ld1rb",
            Ld1rd => "ld1rd",
            Ld1rh => "ld1rh",
            Ld1rob => "ld1rob",
            Ld1rod => "ld1rod",
            Ld1roh => "ld1roh",
            Ld1row => "ld1row",
            Ld1rqb => "ld1rqb",
            Ld1rqd => "ld1rqd",
            Ld1rqh => "ld1rqh",
            Ld1rqw => "ld1rqw",
            Ld1rsb => "ld1rsb",
            Ld1rsh => "ld1rsh",
            Ld1rsw => "ld1rsw",
            Ld1rw => "ld1rw",
            Ld1r => "ld1r",
            Ld2b => "ld2b",
            Ld2d => "ld2d",
            Ld2h => "ld2h",
            Ld2q => "ld2q",
            Ld2r => "ld2r",
            Ld2 => "ld2",
            Ld2w => "ld2w",
            Ld3b => "ld3b",
            Ld3d => "ld3d",
            Ld3h => "ld3h",
            Ld3q => "ld3q",
            Ld3r => "ld3r",
            Ld3 => "ld3",
            Ld3w => "ld3w",
            Ld4b => "ld4b",
            Ld4d => "ld4d",
            Ld4 => "ld4",
            Ld4h => "ld4h",
            Ld4q => "ld4q",
            Ld4r => "ld4r",
            Ld4w => "ld4w",
            Ld64b => "ld64b",
            Ldaddab => "ldaddab",
            Ldaddah => "ldaddah",
            Ldaddalb => "ldaddalb",
            Ldaddalh => "ldaddalh",
            Ldaddal => "ldaddal",
            Ldadda => "ldadda",
            Ldaddb => "ldaddb",
            Ldaddh => "ldaddh",
            Ldaddlb => "ldaddlb",
            Ldaddlh => "ldaddlh",
            Ldaddl => "ldaddl",
            Ldadd => "ldadd",
            Ldap1 => "ldap1",
            Ldaprb => "ldaprb",
            Ldaprh => "ldaprh",
            Ldapr => "ldapr",
            Ldapurb => "ldapurb",
            Ldapurh => "ldapurh",
            Ldapursb => "ldapursb",
            Ldapursh => "ldapursh",
            Ldapursw => "ldapursw",
            Ldapur => "ldapur",
            Ldarb => "ldarb",
            Ldarh => "ldarh",
            Ldar => "ldar",
            Ldaxp => "ldaxp",
            Ldaxrb => "ldaxrb",
            Ldaxrh => "ldaxrh",
            Ldaxr => "ldaxr",
            Ldclrab => "ldclrab",
            Ldclrah => "ldclrah",
            Ldclralb => "ldclralb",
            Ldclralh => "ldclralh",
            Ldclral => "ldclral",
            Ldclra => "ldclra",
            Ldclrb => "ldclrb",
            Ldclrh => "ldclrh",
            Ldclrlb => "ldclrlb",
            Ldclrlh => "ldclrlh",
            Ldclrl => "ldclrl",
            Ldclrp => "ldclrp",
            Ldclrpa => "ldclrpa",
            Ldclrpal => "ldclrpal",
            Ldclrpl => "ldclrpl",
            Ldclr => "ldclr",
            Ldeorab => "ldeorab",
            Ldeorah => "ldeorah",
            Ldeoralb => "ldeoralb",
            Ldeoralh => "ldeoralh",
            Ldeoral => "ldeoral",
            Ldeora => "ldeora",
            Ldeorb => "ldeorb",
            Ldeorh => "ldeorh",
            Ldeorlb => "ldeorlb",
            Ldeorlh => "ldeorlh",
            Ldeorl => "ldeorl",
            Ldeor => "ldeor",
            Ldg => "ldg",
            Ldgm => "ldgm",
            Ldiapp => "ldiapp",
            Ldlarb => "ldlarb",
            Ldlarh => "ldlarh",
            Ldlar => "ldlar",
            Ldnf1b => "ldnf1b",
            Ldnf1d => "ldnf1d",
            Ldnf1h => "ldnf1h",
            Ldnf1sb => "ldnf1sb",
            Ldnf1sh => "ldnf1sh",
            Ldnf1sw => "ldnf1sw",
            Ldnf1w => "ldnf1w",
            Ldnp => "ldnp",
            Ldnt1b => "ldnt1b",
            Ldnt1d => "ldnt1d",
            Ldnt1h => "ldnt1h",
            Ldnt1sb => "ldnt1sb",
            Ldnt1sh => "ldnt1sh",
            Ldnt1sw => "ldnt1sw",
            Ldnt1w => "ldnt1w",
            Ldp => "ldp",
            Ldpsw => "ldpsw",
            Ldraa => "ldraa",
            Ldrab => "ldrab",
            Ldrb => "ldrb",
            Ldr => "ldr",
            Ldrh => "ldrh",
            Ldrsb => "ldrsb",
            Ldrsh => "ldrsh",
            Ldrsw => "ldrsw",
            Ldsetab => "ldsetab",
            Ldsetah => "ldsetah",
            Ldsetalb => "ldsetalb",
            Ldsetalh => "ldsetalh",
            Ldsetal => "ldsetal",
            Ldseta => "ldseta",
            Ldsetb => "ldsetb",
            Ldseth => "ldseth",
            Ldsetlb => "ldsetlb",
            Ldsetlh => "ldsetlh",
            Ldsetl => "ldsetl",
            Ldsetp => "ldsetp",
            Ldsetpa => "ldsetpa",
            Ldsetpal => "ldsetpal",
            Ldsetpl => "ldsetpl",
            Ldset => "ldset",
            Ldsmaxab => "ldsmaxab",
            Ldsmaxah => "ldsmaxah",
            Ldsmaxalb => "ldsmaxalb",
            Ldsmaxalh => "ldsmaxalh",
            Ldsmaxal => "ldsmaxal",
            Ldsmaxa => "ldsmaxa",
            Ldsmaxb => "ldsmaxb",
            Ldsmaxh => "ldsmaxh",
            Ldsmaxlb => "ldsmaxlb",
            Ldsmaxlh => "ldsmaxlh",
            Ldsmaxl => "ldsmaxl",
            Ldsmax => "ldsmax",
            Ldsminab => "ldsminab",
            Ldsminah => "ldsminah",
            Ldsminalb => "ldsminalb",
            Ldsminalh => "ldsminalh",
            Ldsminal => "ldsminal",
            Ldsmina => "ldsmina",
            Ldsminb => "ldsminb",
            Ldsminh => "ldsminh",
            Ldsminlb => "ldsminlb",
            Ldsminlh => "ldsminlh",
            Ldsminl => "ldsminl",
            Ldsmin => "ldsmin",
            Ldtrb => "ldtrb",
            Ldtrh => "ldtrh",
            Ldtrsb => "ldtrsb",
            Ldtrsh => "ldtrsh",
            Ldtrsw => "ldtrsw",
            Ldtr => "ldtr",
            Ldumaxab => "ldumaxab",
            Ldumaxah => "ldumaxah",
            Ldumaxalb => "ldumaxalb",
            Ldumaxalh => "ldumaxalh",
            Ldumaxal => "ldumaxal",
            Ldumaxa => "ldumaxa",
            Ldumaxb => "ldumaxb",
            Ldumaxh => "ldumaxh",
            Ldumaxlb => "ldumaxlb",
            Ldumaxlh => "ldumaxlh",
            Ldumaxl => "ldumaxl",
            Ldumax => "ldumax",
            Lduminab => "lduminab",
            Lduminah => "lduminah",
            Lduminalb => "lduminalb",
            Lduminalh => "lduminalh",
            Lduminal => "lduminal",
            Ldumina => "ldumina",
            Lduminb => "lduminb",
            Lduminh => "lduminh",
            Lduminlb => "lduminlb",
            Lduminlh => "lduminlh",
            Lduminl => "lduminl",
            Ldumin => "ldumin",
            Ldurb => "ldurb",
            Ldur => "ldur",
            Ldurh => "ldurh",
            Ldursb => "ldursb",
            Ldursh => "ldursh",
            Ldursw => "ldursw",
            Ldx => "ldx",
            Ldxp => "ldxp",
            Ldxrb => "ldxrb",
            Ldxrh => "ldxrh",
            Ldxr => "ldxr",
            Ldy => "ldy",
            Ldz => "ldz",
            Ldzi => "ldzi",
            Lslr => "lslr",
            Lsl => "lsl",
            Lsrr => "lsrr",
            Lsr => "lsr",
            Luti2 => "luti2",
            Luti4 => "luti4",
            Mac16 => "mac16",
            Maddpt => "maddpt",
            Madd => "madd",
            Madpt => "madpt",
            Mad => "mad",
            Match => "match",
            Matfp => "matfp",
            Matint => "matint",
            Mlapt => "mlapt",
            Mla => "mla",
            Mls => "mls",
            Setge => "setge",
            Setgen => "setgen",
            Setget => "setget",
            Setgetn => "setgetn",
            Movaz => "movaz",
            Movi => "movi",
            Movk => "movk",
            Movn => "movn",
            Movprfx => "movprfx",
            Movt => "movt",
            Movz => "movz",
            Mrrs => "mrrs",
            Mrs => "mrs",
            Msb => "msb",
            Msr => "msr",
            Msrr => "msrr",
            Msubpt => "msubpt",
            Msub => "msub",
            Mul53hi => "mul53hi",
            Mul53lo => "mul53lo",
            Mul => "mul",
            Mvni => "mvni",
            Nands => "nands",
            Nand => "nand",
            Nbsl => "nbsl",
            Neg => "neg",
            Nmatch => "nmatch",
            Nors => "nors",
            Nor => "nor",
            Not => "not",
            Orns => "orns",
            Orn => "orn",
            Orqv => "orqv",
            Orrs => "orrs",
            Orr => "orr",
            Orv => "orv",
            Pacda => "pacda",
            Pacdb => "pacdb",
            Pacdza => "pacdza",
            Pacdzb => "pacdzb",
            Pacga => "pacga",
            Pacia => "pacia",
            Pacia171615 => "pacia171615",
            Paciasppc => "paciasppc",
            Pacib => "pacib",
            Pacib171615 => "pacib171615",
            Pacibsppc => "pacibsppc",
            Paciza => "paciza",
            Pacizb => "pacizb",
            Pacnbiasppc => "pacnbiasppc",
            Pacnbibsppc => "pacnbibsppc",
            Pext => "pext",
            Pfalse => "pfalse",
            Pfirst => "pfirst",
            Pmov => "pmov",
            Pmullb => "pmullb",
            Pmullt => "pmullt",
            Pmull2 => "pmull2",
            Pmull => "pmull",
            Pmul => "pmul",
            Pnext => "pnext",
            Prfb => "prfb",
            Prfd => "prfd",
            Prfh => "prfh",
            Prfm => "prfm",
            Prfum => "prfum",
            Prfw => "prfw",
            Psel => "psel",
            Ptest => "ptest",
            Ptrues => "ptrues",
            Ptrue => "ptrue",
            Punpkhi => "punpkhi",
            Punpklo => "punpklo",
            Raddhnb => "raddhnb",
            Raddhnt => "raddhnt",
            Raddhn => "raddhn",
            Raddhn2 => "raddhn2",
            Rax1 => "rax1",
            Rbit => "rbit",
            Rcwcas => "rcwcas",
            Rcwcasa => "rcwcasa",
            Rcwcasal => "rcwcasal",
            Rcwcasl => "rcwcasl",
            Rcwcasp => "rcwcasp",
            Rcwcaspa => "rcwcaspa",
            Rcwcaspal => "rcwcaspal",
            Rcwcaspl => "rcwcaspl",
            Rcwclr => "rcwclr",
            Rcwclra => "rcwclra",
            Rcwclral => "rcwclral",
            Rcwclrl => "rcwclrl",
            Rcwclrp => "rcwclrp",
            Rcwclrpa => "rcwclrpa",
            Rcwclrpal => "rcwclrpal",
            Rcwclrpl => "rcwclrpl",
            Rcwsclr => "rcwsclr",
            Rcwsclra => "rcwsclra",
            Rcwsclral => "rcwsclral",
            Rcwsclrl => "rcwsclrl",
            Rcwsclrp => "rcwsclrp",
            Rcwsclrpa => "rcwsclrpa",
            Rcwsclrpal => "rcwsclrpal",
            Rcwsclrpl => "rcwsclrpl",
            Rcwscas => "rcwscas",
            Rcwscasa => "rcwscasa",
            Rcwscasal => "rcwscasal",
            Rcwscasl => "rcwscasl",
            Rcwscasp => "rcwscasp",
            Rcwscaspa => "rcwscaspa",
            Rcwscaspal => "rcwscaspal",
            Rcwscaspl => "rcwscaspl",
            Rcwset => "rcwset",
            Rcwseta => "rcwseta",
            Rcwsetal => "rcwsetal",
            Rcwsetl => "rcwsetl",
            Rcwsetp => "rcwsetp",
            Rcwsetpa => "rcwsetpa",
            Rcwsetpal => "rcwsetpal",
            Rcwsetpl => "rcwsetpl",
            Rcwsset => "rcwsset",
            Rcwsseta => "rcwsseta",
            Rcwssetal => "rcwssetal",
            Rcwssetl => "rcwssetl",
            Rcwssetp => "rcwssetp",
            Rcwssetpa => "rcwssetpa",
            Rcwssetpal => "rcwssetpal",
            Rcwssetpl => "rcwssetpl",
            Rcwswp => "rcwswp",
            Rcwswpa => "rcwswpa",
            Rcwswpal => "rcwswpal",
            Rcwswpl => "rcwswpl",
            Rcwswpp => "rcwswpp",
            Rcwswppa => "rcwswppa",
            Rcwswppal => "rcwswppal",
            Rcwswppl => "rcwswppl",
            Rcwsswp => "rcwsswp",
            Rcwsswpa => "rcwsswpa",
            Rcwsswpal => "rcwsswpal",
            Rcwsswpl => "rcwsswpl",
            Rcwsswpp => "rcwsswpp",
            Rcwsswppa => "rcwsswppa",
            Rcwsswppal => "rcwsswppal",
            Rcwsswppl => "rcwsswppl",
            Rdffrs => "rdffrs",
            Rdffr => "rdffr",
            Rdsvl => "rdsvl",
            Rdvl => "rdvl",
            Ret => "ret",
            Retaa => "retaa",
            Retaasppc => "retaasppc",
            Retabsppc => "retabsppc",
            Rev16 => "rev16",
            Rev32 => "rev32",
            Rev64 => "rev64",
            Revb => "revb",
            Revd => "revd",
            Revh => "revh",
            Revw => "revw",
            Rev => "rev",
            Rmif => "rmif",
            Ror => "ror",
            Rprfm => "rprfm",
            Rshrnb => "rshrnb",
            Rshrnt => "rshrnt",
            Rshrn2 => "rshrn2",
            Rshrn => "rshrn",
            Rsubhnb => "rsubhnb",
            Rsubhnt => "rsubhnt",
            Rsubhn => "rsubhn",
            Rsubhn2 => "rsubhn2",
            Sabalb => "sabalb",
            Sabalt => "sabalt",
            Sabal2 => "sabal2",
            Sabal => "sabal",
            Saba => "saba",
            Sabdlb => "sabdlb",
            Sabdlt => "sabdlt",
            Sabdl2 => "sabdl2",
            Sabdl => "sabdl",
            Sabd => "sabd",
            Sadalp => "sadalp",
            Saddlbt => "saddlbt",
            Saddlb => "saddlb",
            Saddlp => "saddlp",
            Saddlt => "saddlt",
            Saddlv => "saddlv",
            Saddl2 => "saddl2",
            Saddl => "saddl",
            Saddv => "saddv",
            Saddwb => "saddwb",
            Saddwt => "saddwt",
            Saddw2 => "saddw2",
            Saddw => "saddw",
            Sb => "sb",
            Sbclb => "sbclb",
            Sbclt => "sbclt",
            Sbcs => "sbcs",
            Sbc => "sbc",
            Sbfm => "sbfm",
            Sclamp => "sclamp",
            Scvtf => "scvtf",
            Sdivr => "sdivr",
            Sdiv => "sdiv",
            Sdot => "sdot",
            Sdsb => "sdsb",
            Sel => "sel",
            Set => "set",
            Sete => "sete",
            Seten => "seten",
            Setet => "setet",
            Setetn => "setetn",
            Setf16 => "setf16",
            Setf8 => "setf8",
            Setffr => "setffr",
            Setgm => "setgm",
            Setgmn => "setgmn",
            Setgmt => "setgmt",
            Setgmtn => "setgmtn",
            Setgp => "setgp",
            Setgpn => "setgpn",
            Setgpt => "setgpt",
            Setgptn => "setgptn",
            Setm => "setm",
            Setmn => "setmn",
            Setmt => "setmt",
            Setmtn => "setmtn",
            Setp => "setp",
            Setpn => "setpn",
            Setpt => "setpt",
            Setptn => "setptn",
            Sha1c => "sha1c",
            Sha1h => "sha1h",
            Sha1m => "sha1m",
            Sha1p => "sha1p",
            Sha1su0 => "sha1su0",
            Sha1su1 => "sha1su1",
            Sha256h2 => "sha256h2",
            Sha256h => "sha256h",
            Sha256su0 => "sha256su0",
            Sha256su1 => "sha256su1",
            Sha512h => "sha512h",
            Sha512h2 => "sha512h2",
            Sha512su0 => "sha512su0",
            Sha512su1 => "sha512su1",
            Shadd => "shadd",
            Shll2 => "shll2",
            Shll => "shll",
            Shl => "shl",
            Shrnb => "shrnb",
            Shrnt => "shrnt",
            Shrn2 => "shrn2",
            Shrn => "shrn",
            Shsubr => "shsubr",
            Shsub => "shsub",
            Sli => "sli",
            Sm3partw1 => "sm3partw1",
            Sm3partw2 => "sm3partw2",
            Sm3ss1 => "sm3ss1",
            Sm3tt1a => "sm3tt1a",
            Sm3tt1b => "sm3tt1b",
            Sm3tt2a => "sm3tt2a",
            Sm3tt2b => "sm3tt2b",
            Sm4e => "sm4e",
            Sm4ekey => "sm4ekey",
            Smaddl => "smaddl",
            Smaxp => "smaxp",
            Smaxqv => "smaxqv",
            Smaxv => "smaxv",
            Smax => "smax",
            Smc => "smc",
            Sminp => "sminp",
            Sminqv => "sminqv",
            Sminv => "sminv",
            Smin => "smin",
            Smlalb => "smlalb",
            Smlall => "smlall",
            Smlalt => "smlalt",
            Smlal => "smlal",
            Smlal2 => "smlal2",
            Smlslb => "smlslb",
            Smlsll => "smlsll",
            Smlslt => "smlslt",
            Smlsl => "smlsl",
            Smlsl2 => "smlsl2",
            Smmla => "smmla",
            Smopa => "smopa",
            Smops => "smops",
            Smov => "smov",
            Smsubl => "smsubl",
            Smulh => "smulh",
            Smullb => "smullb",
            Smullt => "smullt",
            Smull2 => "smull2",
            Smull => "smull",
            Splice => "splice",
            Sqabs => "sqabs",
            Sqadd => "sqadd",
            Sqcadd => "sqcadd",
            Sqcvtn => "sqcvtn",
            Sqcvtun => "sqcvtun",
            Sqcvtu => "sqcvtu",
            Sqcvt => "sqcvt",
            Sqdecb => "sqdecb",
            Sqdecd => "sqdecd",
            Sqdech => "sqdech",
            Sqdecp => "sqdecp",
            Sqdecw => "sqdecw",
            Sqdmlalbt => "sqdmlalbt",
            Sqdmlalb => "sqdmlalb",
            Sqdmlalt => "sqdmlalt",
            Sqdmlal => "sqdmlal",
            Sqdmlal2 => "sqdmlal2",
            Sqdmlslbt => "sqdmlslbt",
            Sqdmlslb => "sqdmlslb",
            Sqdmlslt => "sqdmlslt",
            Sqdmlsl => "sqdmlsl",
            Sqdmlsl2 => "sqdmlsl2",
            Sqdmulh => "sqdmulh",
            Sqdmullb => "sqdmullb",
            Sqdmullt => "sqdmullt",
            Sqdmull => "sqdmull",
            Sqdmull2 => "sqdmull2",
            Sqincb => "sqincb",
            Sqincd => "sqincd",
            Sqinch => "sqinch",
            Sqincp => "sqincp",
            Sqincw => "sqincw",
            Sqneg => "sqneg",
            Sqrdcmlah => "sqrdcmlah",
            Sqrdmlah => "sqrdmlah",
            Sqrdmlsh => "sqrdmlsh",
            Sqrdmulh => "sqrdmulh",
            Sqrshlr => "sqrshlr",
            Sqrshl => "sqrshl",
            Sqrshrnb => "sqrshrnb",
            Sqrshrnt => "sqrshrnt",
            Sqrshrn => "sqrshrn",
            Sqrshrn2 => "sqrshrn2",
            Sqrshrunb => "sqrshrunb",
            Sqrshrunt => "sqrshrunt",
            Sqrshrun => "sqrshrun",
            Sqrshrun2 => "sqrshrun2",
            Sqrshru => "sqrshru",
            Sqrshr => "sqrshr",
            Sqshlr => "sqshlr",
            Sqshlu => "sqshlu",
            Sqshl => "sqshl",
            Sqshrnb => "sqshrnb",
            Sqshrnt => "sqshrnt",
            Sqshrn => "sqshrn",
            Sqshrn2 => "sqshrn2",
            Sqshrunb => "sqshrunb",
            Sqshrunt => "sqshrunt",
            Sqshrun => "sqshrun",
            Sqshrun2 => "sqshrun2",
            Sqsubr => "sqsubr",
            Sqsub => "sqsub",
            Sqxtnb => "sqxtnb",
            Sqxtnt => "sqxtnt",
            Sqxtn2 => "sqxtn2",
            Sqxtn => "sqxtn",
            Sqxtunb => "sqxtunb",
            Sqxtunt => "sqxtunt",
            Sqxtun2 => "sqxtun2",
            Sqxtun => "sqxtun",
            Srhadd => "srhadd",
            Sri => "sri",
            Srshlr => "srshlr",
            Srshl => "srshl",
            Srshr => "srshr",
            Srsra => "srsra",
            Sshllb => "sshllb",
            Sshllt => "sshllt",
            Sshll2 => "sshll2",
            Sshll => "sshll",
            Sshl => "sshl",
            Sshr => "sshr",
            Ssra => "ssra",
            St1b => "st1b",
            St1d => "st1d",
            St1h => "st1h",
            St1q => "st1q",
            St1w => "st1w",
            Ssublbt => "ssublbt",
            Ssublb => "ssublb",
            Ssubltb => "ssubltb",
            Ssublt => "ssublt",
            Ssubl2 => "ssubl2",
            Ssubl => "ssubl",
            Ssubwb => "ssubwb",
            Ssubwt => "ssubwt",
            Ssubw2 => "ssubw2",
            Ssubw => "ssubw",
            St1 => "st1",
            St2b => "st2b",
            St2d => "st2d",
            St2g => "st2g",
            St2h => "st2h",
            St2q => "st2q",
            St2 => "st2",
            St2w => "st2w",
            St3b => "st3b",
            St3d => "st3d",
            St3h => "st3h",
            St3q => "st3q",
            St3 => "st3",
            St3w => "st3w",
            St4b => "st4b",
            St4d => "st4d",
            St4 => "st4",
            St4h => "st4h",
            St4q => "st4q",
            St4w => "st4w",
            St64b => "st64b",
            St64bv => "st64bv",
            St64bv0 => "st64bv0",
            Stadd => "stadd",
            Stclr => "stclr",
            Steorl => "steorl",
            Steor => "steor",
            Stsetl => "stsetl",
            Stset => "stset",
            Stsmaxl => "stsmaxl",
            Stsmax => "stsmax",
            Stsminl => "stsminl",
            Stsmin => "stsmin",
            Stumax => "stumax",
            Stumin => "stumin",
            Stgm => "stgm",
            Stgp => "stgp",
            Stg => "stg",
            Stilp => "stilp",
            Stl1 => "stl1",
            Stllrb => "stllrb",
            Stllrh => "stllrh",
            Stllr => "stllr",
            Stlrb => "stlrb",
            Stlrh => "stlrh",
            Stlr => "stlr",
            Stlurb => "stlurb",
            Stlurh => "stlurh",
            Stlur => "stlur",
            Stlxp => "stlxp",
            Stlxrb => "stlxrb",
            Stlxrh => "stlxrh",
            Stlxr => "stlxr",
            Stnp => "stnp",
            Stnt1b => "stnt1b",
            Stnt1d => "stnt1d",
            Stnt1h => "stnt1h",
            Stnt1w => "stnt1w",
            Stp => "stp",
            Strb => "strb",
            Str => "str",
            Strh => "strh",
            Sttrb => "sttrb",
            Sttrh => "sttrh",
            Sttr => "sttr",
            Sturb => "sturb",
            Stur => "stur",
            Sturh => "sturh",
            Stx => "stx",
            Stxp => "stxp",
            Stxrb => "stxrb",
            Stxrh => "stxrh",
            Stxr => "stxr",
            Sty => "sty",
            Stz => "stz",
            Stz2g => "stz2g",
            Stzgm => "stzgm",
            Stzg => "stzg",
            Stzi => "stzi",
            Subg => "subg",
            Subhnb => "subhnb",
            Subhnt => "subhnt",
            Subhn => "subhn",
            Subhn2 => "subhn2",
            Subp => "subp",
            Subps => "subps",
            Subpt => "subpt",
            Subr => "subr",
            Subs => "subs",
            Sub => "sub",
            Sudot => "sudot",
            Sumlall => "sumlall",
            Sumopa => "sumopa",
            Sumops => "sumops",
            Sunpkhi => "sunpkhi",
            Sunpklo => "sunpklo",
            Sunpk => "sunpk",
            Suqadd => "suqadd",
            Suvdot => "suvdot",
            Svc => "svc",
            Svdot => "svdot",
            Swpab => "swpab",
            Swpah => "swpah",
            Swpalb => "swpalb",
            Swpalh => "swpalh",
            Swpal => "swpal",
            Swpa => "swpa",
            Swpb => "swpb",
            Swph => "swph",
            Swplb => "swplb",
            Swplh => "swplh",
            Swpl => "swpl",
            Swpp => "swpp",
            Swppa => "swppa",
            Swppal => "swppal",
            Swppl => "swppl",
            Swp => "swp",
            Sxtb => "sxtb",
            Sxth => "sxth",
            Sxtw => "sxtw",
            Sysl => "sysl",
            Sysp => "sysp",
            Sys => "sys",
            Tlbi => "tlbi",
            At => "at",
            Dc => "dc",
            Ic => "ic",
            Tblq => "tblq",
            Tbl => "tbl",
            Tbnz => "tbnz",
            Tbxq => "tbxq",
            Tbx => "tbx",
            Tbz => "tbz",
            Tcancel => "tcancel",
            Tcommit => "tcommit",
            Trcit => "trcit",
            Trn1 => "trn1",
            Trn2 => "trn2",
            Tsb => "tsb",
            Tstart => "tstart",
            Ttest => "ttest",
            Uabalb => "uabalb",
            Uabalt => "uabalt",
            Uabal2 => "uabal2",
            Uabal => "uabal",
            Uaba => "uaba",
            Uabdlb => "uabdlb",
            Uabdlt => "uabdlt",
            Uabdl2 => "uabdl2",
            Uabdl => "uabdl",
            Uabd => "uabd",
            Uadalp => "uadalp",
            Uaddlb => "uaddlb",
            Uaddlp => "uaddlp",
            Uaddlt => "uaddlt",
            Uaddlv => "uaddlv",
            Uaddl2 => "uaddl2",
            Uaddl => "uaddl",
            Uaddv => "uaddv",
            Uaddwb => "uaddwb",
            Uaddwt => "uaddwt",
            Uaddw2 => "uaddw2",
            Uaddw => "uaddw",
            Ubfm => "ubfm",
            Uclamp => "uclamp",
            Ucvtf => "ucvtf",
            Udf => "udf",
            Udivr => "udivr",
            Udiv => "udiv",
            Udot => "udot",
            Uhadd => "uhadd",
            Uhsubr => "uhsubr",
            Uhsub => "uhsub",
            Umaddl => "umaddl",
            Umaxp => "umaxp",
            Umaxqv => "umaxqv",
            Umaxv => "umaxv",
            Umax => "umax",
            Uminp => "uminp",
            Uminqv => "uminqv",
            Uminv => "uminv",
            Umin => "umin",
            Umlalb => "umlalb",
            Umlall => "umlall",
            Umlalt => "umlalt",
            Umlal => "umlal",
            Umlal2 => "umlal2",
            Umlslb => "umlslb",
            Umlsll => "umlsll",
            Umlslt => "umlslt",
            Umlsl => "umlsl",
            Umlsl2 => "umlsl2",
            Ummla => "ummla",
            Umopa => "umopa",
            Umops => "umops",
            Umov => "umov",
            Umsubl => "umsubl",
            Umulh => "umulh",
            Umullb => "umullb",
            Umullt => "umullt",
            Umull2 => "umull2",
            Umull => "umull",
            Uqadd => "uqadd",
            Uqcvtn => "uqcvtn",
            Uqcvt => "uqcvt",
            Uqdecb => "uqdecb",
            Uqdecd => "uqdecd",
            Uqdech => "uqdech",
            Uqdecp => "uqdecp",
            Uqdecw => "uqdecw",
            Uqincb => "uqincb",
            Uqincd => "uqincd",
            Uqinch => "uqinch",
            Uqincp => "uqincp",
            Uqincw => "uqincw",
            Uqrshlr => "uqrshlr",
            Uqrshl => "uqrshl",
            Uqrshrnb => "uqrshrnb",
            Uqrshrnt => "uqrshrnt",
            Uqrshrn => "uqrshrn",
            Uqrshrn2 => "uqrshrn2",
            Uqrshr => "uqrshr",
            Uqshlr => "uqshlr",
            Uqshl => "uqshl",
            Uqshrnb => "uqshrnb",
            Uqshrnt => "uqshrnt",
            Uqshrn => "uqshrn",
            Uqshrn2 => "uqshrn2",
            Uqsubr => "uqsubr",
            Uqsub => "uqsub",
            Uqxtnb => "uqxtnb",
            Uqxtnt => "uqxtnt",
            Uqxtn2 => "uqxtn2",
            Uqxtn => "uqxtn",
            Urecpe => "urecpe",
            Urhadd => "urhadd",
            Urshlr => "urshlr",
            Urshl => "urshl",
            Urshr => "urshr",
            Ursqrte => "ursqrte",
            Ursra => "ursra",
            Usdot => "usdot",
            Ushllb => "ushllb",
            Ushllt => "ushllt",
            Ushll2 => "ushll2",
            Ushll => "ushll",
            Ushl => "ushl",
            Ushr => "ushr",
            Usmlall => "usmlall",
            Usmmla => "usmmla",
            Usmopa => "usmopa",
            Usmops => "usmops",
            Usqadd => "usqadd",
            Usra => "usra",
            Usublb => "usublb",
            Usublt => "usublt",
            Usubl2 => "usubl2",
            Usubl => "usubl",
            Usubwb => "usubwb",
            Usubwt => "usubwt",
            Usubw2 => "usubw2",
            Usubw => "usubw",
            Usvdot => "usvdot",
            Uunpkhi => "uunpkhi",
            Uunpklo => "uunpklo",
            Uunpk => "uunpk",
            Uvdot => "uvdot",
            Uxtb => "uxtb",
            Uxth => "uxth",
            Uxtw => "uxtw",
            Uzp1 => "uzp1",
            Uzp2 => "uzp2",
            Uzpq1 => "uzpq1",
            Uzpq2 => "uzpq2",
            Uzp => "uzp",
            Vecfp => "vecfp",
            Vecint => "vecint",
            Wfet => "wfet",
            Wfit => "wfit",
            Whilege => "whilege",
            Whilegt => "whilegt",
            Whilehi => "whilehi",
            Whilehs => "whilehs",
            Whilele => "whilele",
            Whilelo => "whilelo",
            Whilels => "whilels",
            Whilelt => "whilelt",
            Whilerw => "whilerw",
            Whilewr => "whilewr",
            Wkdmc => "wkdmc",
            Wkdmd => "wkdmd",
            Wrffr => "wrffr",
            Xaflag => "xaflag",
            Xar => "xar",
            Xpacd => "xpacd",
            Xpaci => "xpaci",
            Xtn2 => "xtn2",
            Xtn => "xtn",
            Zero => "zero",
            Zip1 => "zip1",
            Zip2 => "zip2",
            Zipq1 => "zipq1",
            Zipq2 => "zipq2",
            Zip => "zip",
            Nop => "nop",
            Yield => "yield",
            Wfe => "wfe",
            Wfi => "wfi",
            Sev => "sev",
            Sevl => "sevl",
            Paciasp => "paciasp",
            Pacibsp => "pacibsp",
            Autia1716 => "autia1716",
            Autib1716 => "autib1716",
            Autiasp => "autiasp",
            Autibsp => "autibsp",
            Retab => "retab",
            Retabsp => "retaasp",
            Bcond => "b",
            Cmn => "cmn",
            Tst => "tst",
            Negs => "negs",
            Mvn => "mvn",
            Cset => "cset",
            Csetm => "csetm",
            Cinc => "cinc",
            Cinv => "cinv",
            Cneg => "cneg",
            Mneg => "mneg",
            Cmp => "cmp",
            Undefined => ".inst",
        }
    }
}

// 1422 mnemonics